package com.drpicox.game.world;

public class DefaultWorldFactory {

    public World create() {
        return new TextWorldFactory().create(
                " ============ rooms:",
                "0 0:Bienvenida:-1 -1 0 -1:diario",
                "Bienvenido a este juego de aventura. ",
                "Esta es la habitacion de bienvenida, donde aprenderas a moverte. ",
                "Los comandos son:",
                " 'norte',",
                " 'sur',",
                " 'este',",
                " 'oeste'. ",
                "Prueba de ir a la siguiente habitacion al 'este', y volver al 'oeste'.",
                "::::",
                "0 1:Usa las llaves:0111 -1 -1 0:llave de laton",
                "En esta sala aprenderas a coger objetos y abrir puertas con llave. ",
                "Los comandos son:",
                " 'coger',",
                " y los de movimiento.",
                "Si vas al norte directamente no podras, intentalo.",
                "Despues coge la llave ('coger') y ves hacia el norte.",
                "::::",
                "0 2:Comedor sur:0 -1 0 -1:mosca",
                "Es el ala sur de tu comedor. La luz entra difusa desde la salita y",
                "las sillas esperan a tus invitados.",
                "::::",
                "0 3:Salita:0 -1 -1 0:polilla",
                "Es la salita de tu casa, la luz entra por la ventana y las cortinas",
                "desdibujan el exterior. Puedes ver tu sillon, una mesita con un ",
                "candelabro y estanterias con varios libros.",
                "::::",
                "0 4:Huerto de pepinos:0 -1 0 -1:nada",
                "Junto a la verja sur de tu granja tienes el huerto de pepinos. ",
                "Apenas levantan un dedo del suelo, pero ya te relames pensando",
                "en su sabor.",
                "::::",
                "0 5:Huerto de tomates:0 -1 0 0:nada",
                "Junto a la verja sur de tu granja tienes el huerto de tomates. Aun",
                "estan verdes, pero parece que este anyo tendras muy buena cosecha.",
                "::::",
                "0 6:Caminito:-1 -1 0 0:nada",
                "Un bonito caminito se alarga hacia el este, la parte mas alejada ",
                "de tu granja.",
                "::::",
                "0 7:Caminito:0 -1 -1 0:planta carnivora",
                "Es el fin de tu caminito, al norte tienes las plantaciones frutales.",
                "Siempre te gusta pasear en primavera y ver las flores.",
                "::::",
                "1 0:Despensa:0 -1 -1 -1:nada",
                "Al fin has podido entrar en la despensa!",
                "Ahora ya puedes empezar a preparar la comida para tus comensales.",
                "FELICIDADES!",
                "::::",
                "1 1:Aprende a atacar:-1 0 1112 -1:mosca acida",
                "Es hora de que aprendas a atacar a tus enemigos. Debes ir con cuidado",
                "ya que ellos se defenderan.",
                "Solo hay un comando:",
                " 'atacar'.",
                "Para ello debes conseguir primero un arma. Busca una, cogela y ataca.",
                "Cuando venzas podras continuar.",
                "::::",
                "1 2:Comedor:0 0 0 -1:nada",
                "Estas en el comedor de tu casa, fuera hace un dia fantastico y",
                "esperas visita. Hoy tienes decidido preparar un buen banquete!",
                "La entrada esta al oeste, la salita al sur, y la cocina al oeste.",
                "::::",
                "1 3:Recibidor:0 0 1314 0:mosca",
                "Es un recibidor pequenyo pero acogedor. Esta decorado austeramente",
                "pero dispone de colgarropas para dejar la chaqueta.",
                "Desde el puedes acceder directamente a la salita, al comedor y a la",
                "cocina.",
                "::::",
                "1 4:Patio:0 0 0 0:nada",
                "Hace un dia esplendido y estas en el jardin de tu granja. Aqui puedes",
                "ver varias flores que has plantado y una fuente. Te rodean varios ",
                "huertos y mas lejos al este tienes los frutales.",
                "::::",
                "1 5:Huerto de Judias:-1 0 -1 0:raton salvaje",
                "Un bonito huerto de judias se abre delante de ti. Hace apenas unas",
                "semanas que las plantaste, pero ya estan florecidas. El fuerte color",
                "amarillo de las flores contrastan con el verde de las plantas.",
                "::::",
                "1 6:Manzanos:0 -1 0 -1:raton",
                "Este es tu cultivo de manzanas. Este anyo las lluvias han sido ",
                "generosas y tendras una buena cosecha. Hay ya alguna manzana, pero",
                "a mayoria demasiado verdes.",
                "::::",
                "1 7:Ciruelos:0 0 -1 0:nada",
                "Siempre te ha gustado esta parte de la granja. Los ciruelos tienen",
                "hojas rojas y le dan un aspecto muy fresco. El rio esta hacia el norte,",
                "y tu casa hacia el suroeste.",
                "::::",
                "2 0:Banyo:-1 2010 0 -1:mosca",
                "Este es el banyo de tu casa. Es mas bien rustico pero funcional. La ",
                "banyera la compraste recientemente y al lado tienes bien ordenadas",
                "las toallas. Al sur esta la despensa.",
                "::::",
                "2 1:Habitacion:-1 -1 0 0:mosquito",
                "Es la habitacion donde duermes. Tienes una cama de madera trabajada,",
                "con numerosas mantas que te protegen del frio, y un tocador donde ",
                "guardas tu ropa. Dese la habitacion puedes acceder al comedor y al",
                "lavabo.",
                "::::",
                "2 2:Comedor norte:-1 0 0 0:nada",
                "Es la parte norte de tu gran comedor. La mesa para la ocasion se ",
                "extiende y todos los servicios estan en su sitio. Desde aqui puedes",
                "acceder a la cocina y a tu habitacion.",
                "::::",
                "2 3:Cocina:-1 0 -1 0:cucaracha",
                "Esta es tu cocina. Estas contento con tu nuevo horno de lenya, cocina",
                "a las mil maravillas. Tienes todo preparado para hacer la comida, ",
                "pero te faltan los ingredientes. Tendrias que recogerlos de la ",
                "despensa.",
                "::::",
                "2 4:Huerto de calabazas:-1 0 -1 -1:escorpion dorado",
                "Este es tu huerto de calabazas. Apenas han empezado a crecer pero ",
                "dependes de ellas para comer este otonyo. No puedes evitar pensar",
                "si te has de llevar alguna a tus padres.",
                "::::",
                "2 5:Naranjos:-1 -1 0 -1:naranja",
                "Aqui tienes uno de los cultivos mas sufridos. No sueles tener ",
                "demasiadas naranjas, pero te gustan demasiado. Su color y aroma",
                "te resultan estupendas.",
                "::::",
                "2 6:Entrada:2636 0 0 0:rana venenosa",
                "Aqui esta la entrada norte de tu granja. La coronan dos magnificos ",
                "cipreses y numerosos arbustos. La reja la sueles tener cerrada, ",
                "nunca te ha gustado adentrarte en el bosque. Al norte esta el rio.",
                "::::",
                "2 7:Nogal:-1 0 -1 0:raton",
                "Unos grandes nogales se extienden es este cultivo de tu granja. ",
                "Son especialmente interesantes, porque, aunque su fruto no sea tan",
                "bueno como las manzanas, son resistentes y te permiten superar los",
                "inviernos.",
                "::::",
                "3 0:Cueva:0 -1 0 -1:murcielago",
                "Sigue el tunel de la cueva oscura y sombria. Las paredes estan ",
                "humedas y se escucha un rumor de agua a lo lejos. Has de caminar",
                "con cuidado para no resbalar o tropezar.",
                "::::",
                "3 1:Cueva:0 -1 -1 0:nada",
                "Sigue el tunel de la cueva oscura y sombria. Las paredes estan ",
                "humedas y se escucha un rumor de agua a lo lejos. Has de caminar",
                "con cuidado para no resbalar o tropezar.",
                "::::",
                "3 2:Lago interno:0 -1 3233 -1:nada",
                "Un inmenso lago interior se abre delante tuyo. Esta oscuro y ",
                "apenas se ve bien, pero intuyes que algo se mueve al este. ",
                "Necesitas una barca para ir al centro del lago.",
                "::::",
                "3 3:Centro del lago:-1 -1 -1 0:monstruo aquatico enorme",
                "Estas en el centro del lago con una pequenya y fragil barca.",
                "Es hogar de Troildhem, un increible monstruo misterioso. ",
                "Ya habias visto otro igual antes, pero mas pequenyo.",
                "Troildhem tiene varios metros de altura, y una decena de ",
                "tentaculos con hojos.",
                "::::",
                "3 4:Rio salvaje:3444 -1 0 -1:espada",
                "Aqui el rio se hace mas salvaje, sin embargo hay un puente que ",
                "te permite pasar con segurida a la otra orilla. El puente se debe",
                "desbloquear con una llave para poder pasar.",
                "::::",
                "3 5:Rio:-1 -1 0 0:trucha asesina",
                "Por aqui discurre el rio. No puedes cruzar, pero mas al oeste",
                "hay un puente.",
                "::::",
                "3 6:Rio:-1 0 0 0:nada",
                "Tu granja va a parar a este rio. En el norte esta el bosque ",
                "misterioso pero no puedes cruzar por aqui.",
                "::::",
                "3 7:Rio:-1 -1 -1 0:minimonstruo aquatico",
                "El rio se ensancha y sus aguas se tranquilizan, hay numerosos",
                "peces pero algo se remueve enre las aguas.",
                "::::",
                "4 0:Cueva:0 0 -1 -1:nada",
                "Sigue el tunel de la cueva oscura y sombria. Las paredes estan ",
                "humedas y se escucha un rumor de agua a lo lejos. Has de caminar",
                "con cuidado para no resbalar o tropezar.",
                "::::",
                "4 1:Cueva:0 0 -1 -1:murcielago",
                "Sigue el tunel de la cueva oscura y sombria. Las paredes estan ",
                "humedas y se escucha un rumor de agua a lo lejos. Has de caminar",
                "con cuidado para no resbalar o tropezar.",
                "::::",
                "4 2:Cueva:0 0 -1 -1:nada",
                "Sigue el tunel de la cueva oscura y sombria. Las paredes estan ",
                "humedas y se escucha un rumor de agua a lo lejos. Has de caminar",
                "con cuidado para no resbalar o tropezar.",
                "::::",
                "4 3:Bosque oscuro:0 -1 -1 -1:lobo",
                "A pesar de ser de dia apenas llega un apice de luz. Arbustos, ",
                "arboles y zarzas dificultan el paso. Algo se mueve en la ",
                "oscuridad.",
                "::::",
                "4 4:Rio salvaje:-1 0 0 -1:nada",
                "La orilla norte del rio es lugubre. Se escuchan extranyos ruidos",
                "y se intuye una maldicion. Aqui esta el punte que cruza a la ",
                "orilla sur, el ambiente parece hostil e invita cruzarlo.",
                "::::",
                "4 5:Rio oscuro:-1 -1 0 0:trucha",
                "El rio fluye bajo las rocas y raizes de los arboles del bosque.",
                "Los sonios del bosque se intensifican y te sientes vigilado.",
                "::::",
                "4 6:Bosque tenebroso:0 -1 -1 0:nada",
                "Una brecha entre zarzas y arbustos te da la entrada al bosque",
                "tenebroso. La luz escasea y las sombras son amenazadoras.",
                "::::",
                "4 7:Bosque oscuro:0 -1 -1 -1:ogro",
                "A pesar de ser de dia apenas llega un apice de luz. Arbustos, ",
                "arboles y zarzas dificultan el paso. Algo se mueve en la ",
                "oscuridad.",
                "::::",
                "5 0:Cueva:0 0 -1 -1:aranya gigante",
                "Sigue el tunel de la cueva oscura y sombria. Una gran telaranya",
                "dificulta el paso hacia el sud. Un movimiento poco cuidadoso te",
                "podria hacer presa de ella.",
                "::::",
                "5 1:Cueva:-1 0 0 -1:nada",
                "Sigue el tunel de la cueva oscura y sombria. Las paredes estan ",
                "humedas y se escucha un rumor de agua a lo lejos. Has de caminar",
                "con cuidado para no resbalar o tropezar.",
                "::::",
                "5 2:Cueva:-1 0 -1 0:vampiro",
                "Sigue el tunel de la cueva oscura y sombria. Las paredes estan ",
                "humedas, y el rumor de agua se magnifica. Has de caminar con cuidado ",
                "para no resbalar o tropezar.",
                "::::",
                "5 3:Bosque sombrio:0 0 -1 -1:nada",
                "El bosque es oscuro y junto a ti has descubierto un gran pared ",
                "de roca solida al oeste, probablemente la montanya. ",
                "::::",
                "5 4:Bosque humedo:0 -1 0 -1:nada",
                "La luz escasea entre las hojas de los arboles. Zarzas y arbustos",
                "dan paso a un pequenyo riachuelo. Algo se mueve en la oscuridad.",
                "::::",
                "5 5:Bosque:-1 -1 0 0:nada",
                "El bosque se extiende oscuro y misterioso. La luz se desdibuja a",
                "traves de las hojas. Se escuchan los ruidos de los animales y",
                "sus otros habitantes.",
                "::::",
                "5 6:Claro del Bosque:0 0 -1 0:nada",
                "El bosque se extiende oscuro y misterioso. Estas en un pequenyo",
                "claro del bosque donde se puede contemplar el cielo. Notas que",
                "el bosque esta agitado.",
                "::::",
                "5 7:Bosque:0 0 -1 -1:nada",
                "El bosque se extiende oscuro y misterioso. La luz se desdibuja a",
                "traves de las hojas. Se escuchan los ruidos de los animales y",
                "sus otros habitantes.",
                "::::",
                "6 0:Cueva:0 0 -1 -1:nada",
                "Sigue el tunel de la cueva oscura y sombria. Las paredes estan ",
                "humedas y se escucha un rumor de agua a lo lejos. Has de caminar",
                "con cuidado para no resbalar o tropezar.",
                "::::",
                "6 1:Cueva:0 -1 0 -1:nada",
                "Sigue el tunel de la cueva oscura y sombria. Las paredes estan ",
                "humedas y se escucha un rumor de agua a lo lejos. Has de caminar",
                "con cuidado para no resbalar o tropezar.",
                "::::",
                "6 2:Cueva:0 -1 -1 0:murcielago",
                "Estas dentro de la cueva, es oscura y sombria. Las paredes estan ",
                "humedas y se escucha un rumor de agua a lo lejos. Intentas mirar",
                "pero parece que no tiene fin.",
                "::::",
                "6 3:Bosque sombrio:0 0 0 -1:nada",
                "El bosque es oscuro y junto a ti has descubierto un gran pared ",
                "de roca solida al oeste, probablemente la montanya. Notas que la",
                "roca esta humeda, muy probablemente haya alguna cueva.",
                "::::",
                "6 4:Puente del bosque:0 0 -1 0:4636:gnomo del puente",
                "La luz escasea entre las hojas de los arboles. Zarzas y arbustos",
                "dan paso a un pequenyo riachuelo. Un puente cruza el riachuelo y",
                "permite alcanzar la parte este del bosque, alli, bajo un arbol",
                "hay la casa de un troll que tenras que atravesar si quieres ir",
                "al este.",
                "::::",
                "6 5:Bosque oscuro:-1 -1 0 -1:lobo asesino",
                "A pesar de ser de dia apenas llega un apice de luz. Arbustos, ",
                "arboles y zarzas dificultan el paso. Algo se mueve en la ",
                "oscuridad.",
                "::::",
                "6 6:Claro del Bosque:-1 0 0 0:nada",
                "El bosque se extiende oscuro, misterioso y agitado. Estas en un ",
                "pequenyo claro del bosque donde se puede contemplar el cielo. ",
                "::::",
                "6 7:Bosque:0 0 -1 0:nada",
                "En esta parte del bosque la luz empieza a escasear. Maranyas de",
                "arbustos y zarzales dificultan tus pasos. Notas que algo se mueve",
                "entre las sombras.",
                "::::",
                "7 0:Cueva:-1 0 0 -1:nada",
                "Sigue el tunel de la cueva oscura y sombria. Las paredes estan ",
                "humedas y se escucha un rumor de agua a lo lejos. Has de caminar",
                "con cuidado para no resbalar o tropezar.",
                "::::",
                "7 1:Cueva:-1 0 -1 0:aranya",
                "Sigue el tunel de la cueva oscura y sombria. Las paredes estan ",
                "humedas y se escucha un rumor de agua a lo lejos. Has de caminar",
                "con cuidado para no resbalar o tropezar.",
                "::::",
                "7 2:Cueva:-1 0 0 -1:nada",
                "Estas en los primeros pasos dentro de la cueva. Aire frio y",
                "humedo te invade de su interior. Intentas ver donde se acaba, ",
                "pero no puedes. Oyes murmullos provinientes de lo mas profundo.",
                "::::",
                "7 3:Bosque:-1 0 -1 0:nada",
                "La luz escasea entre las hojas de los arboles. Un grupo de ",
                "plantas trepadoras se mueven al oeste, es la entrada a una ",
                "cueva. Sientes una presencia que te observa.",
                "::::",
                "7 4:Bosque humedo:-1 0 0 -1:nada",
                "La luz escasea entre las hojas de los arboles. Zarzas y arbustos",
                "dan paso a un pequenyo riachuelo. Algo se mueve en la oscuridad.",
                "::::",
                "7 5:Bosque:-1 -1 0 0:lobo",
                "El bosque se extiende oscuro y misterioso. La luz se desdibuja a",
                "traves de las hojas. Se escuchan los ruidos de los animales y",
                "sus otros habitantes.",
                "::::",
                "7 6:Bosque:-1 -1 0 0:nada",
                "El bosque se extiende oscuro y misterioso. La luz se desdibuja a",
                "traves de las hojas. Se escuchan los ruidos de los animales y",
                "sus otros habitantes.",
                "::::",
                "7 7:Bosque:-1 0 -1 0:lobo",
                "El bosque se extiende oscuro y misterioso. La luz se desdibuja a",
                "traves de las hojas. Se escuchan los ruidos de los animales y",
                "sus otros habitantes.",
                "::::",
                " ============ items:",
                "llave de laton:         KEY    0111",
                "cristal magico:         KEY    1112",
                "llave de casa:          KEY    1314",
                "llave de la verja:      KEY    2636",
                "llave del puente:       KEY    3444",
                "llave del gnomo:        KEY    4636",
                "barca:                  KEY    3233",
                "llave de la despensa:   KEY    2010",
                "diario:                 WEAPON    1",
                "matamoscas:             WEAPON    2",
                "espada de madera:       WEAPON    4",
                "espada:                 WEAPON    8",
                "espada venenosa:        WEAPON   12",
                "Thurmei:                WEAPON   16",
                "camisa:                 SHIELD    2",
                "escudo de madera:       SHIELD    4",
                "escudo de escamas:      SHIELD    8",
                "escudo:                 SHIELD   12",
                "Rharmei:                SHIELD   16",
                // "caramelo:               FOOD      2",
                // "judia:                  FOOD      4",
                // "manzana:                FOOD      8",
                // "naranja:                FOOD     12",
                // "pocima:                 FOOD     16",
                " ============ monsters:",
                "=== Bienvenida:           0  0:===",
                "mosca acida:              4  0:cristal magico",
                "mosca:                    0  0:caramelo",
                "mosquito:                 2  0:matamoscas",
                "polilla:                  1  1:camisa",
                "cucaracha:                1  1:llave de casa",
                "=== Bosque:               0  0:===",
                "raton:                    2  2:judia",
                "rana venenosa:            2  1:espada de madera",
                "planta carnivora:         1  3:escudo de madera",
                "raton salvaje:            3  3:llave de la verja",
                "escorpion dorado:        12  2:espada venenosa",
                "=== Rio:                  0  0:===",
                "trucha:                   3  3:manzana",
                "trucha asesina:           4  7:escudo de escamas",
                "minimonstruo aquatico:    8  4:llave del puente",
                "=== Bosque:               0  0:===",
                "lobo:                     8  6:manzana",
                "lobo asesino:            12  7:escudo",
                "ogro:                     6 10:naranja",
                "gnomo de puente:         11 11:llave del gnomo",
                "=== Cueva:                0  0:===",
                "murcielago:               8  8:judia",
                "aranya:                  14  4:Thurmei",
                "vampiro:                 12 13:Rharmei",
                "aranya gigante:          14 14:barca",
                "monstruo aquatico enorme:32 15:llave de la despensa"
        );
    }

}
